# Generated by Django 4.0.6 on 2022-09-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_user_alter_prospect_city_alter_prospect_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
