# Generated by Django 4.0.6 on 2022-09-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.offers'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.year'),
        ),
    ]
